### PR TITLE
New build process

### PR DESCRIPTION
**Pull request by hdngr**
Re-scaffolds application and uses yeoman (bower, grunt) to manage dependencies and build process.

gh-pages task builds site into gh-pages branch automatically.  See the [gh-pages branch on this fork](https://github.com/hustonhedinger/graphgist/tree/gh-pages) for an example of how this works.

TODO
- Build vendor and main css instead of using cdns
- Use grunt for dev server with reloader and watch tasks

### CODE REVIEW

**Comment by nawroth** [comment]
While it adds a bit of complexity, I think this is the way we have to go.
Loading less files to bring the depenencies in is good.
It's still possible to check out the gh-pages branch to try out changes without using the build tools -- let's add that to the readme (which should really be AsciiDoc!)

The TODO items above are the ones I was going to to ask for ;-)

It seems to work well: http://hustonhedinger.github.io/graphgist/

The different versions of the CodeMirror dependecies are most likely just a mistake by me.
Should be updated to 4.5.0 now.

The license of the project should be Apache 2.

Why move the javascripts to the end of the body instead of in the head?
We don't optimze for the HTML to show up fast, we optimize for starting to load the content using JS as fast as possible.
So to me it makes more sense to me to load the JS in the head then.

WDYT? @hustonhedinger @jexp

**Comment by hdngr** [comment]
- @nawroth OK great - I will likely get to the TODOs this weekend.
- Re: http://hustonhedinger.github.io/graphgist/ - lol, I did not even think to check my gh-pages - I just ran a local static server and assumed it worked, way to think out side the box! ;-)
- Re loading of <script> - absolutely, you are right, you are optimizing for something different here - I will factor that in.

Any way these things can get ticketed?  Feel free to assign to me...

I'll leave this PR open, and keep pushing to this branch.

Best,

-Huston

**Comment by nawroth** [comment]
To get really good load times, we could use HTML5 appcache (see http://appcachefacts.info/), maybe using https://www.npmjs.org/package/grunt-manifest. I'm using that in a different project, it's amazing!

We could also add code that tells the user when a new version of GraphGist is available upon page reload.

**Comment by hdngr** [comment]
Take a look: 
http://hustonhedinger.github.io/graphgist/

@nawroth @jexp this is ready to go guys, unless you find bugs.

When this gets merged I can work on including Alchemy.js

**Comment by nawroth** [comment]
From a quick look, it still says it's MIT or BSD-2-Clause licensed (in different files), which should be Apache2. I'll have a closer look later.

**Comment by hdngr** [comment]
@nawroth - done, thanks - let me know what else you need.  Would be great to get this done shortly with GC coming up...  thanks!

**Comment by nawroth** [comment]
@hustonhedinger 
Could you send in a CLA, I couldn't find one from you?
http://docs.neo4j.org/chunked/stable/cla.html

I've got some more cleanup, I'll do a PR for your PR in a moment.

**Comment by hdngr** [comment]
Yes - just signed.

**Comment by nawroth** [comment]
Thanks for the CLA. Here's my PR for you! https://github.com/hustonhedinger/graphgist/pull/1

**Comment by nawroth** [comment]
Oh, and I've got a question: how do I make sure the app/vendor dir is refreshed when I pull in updates from git? I had problems with outdates stuff in there when trying out `grunt serve`. Would like to add that to the readme at some point.

**Comment by hdngr** [comment]
The `app/vendor` directory is built locally for everyone from the `bower.json` file.  So, running `bower install` should take care of keeping all dependencies in order.  Does that make sense?

Worst comes to worst you can always torch the vendor directory and rerun `bower install` to bring things back up to date.  

Feel free to ping me if you have any problems...

**Comment by nawroth** [comment]
I'll add that to the readme, for other people who are bower noobs!

**Pull request merged**
